language: android

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra

jdk:
    - oraclejdk8

before_cache:
    - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
    - ./gradlew assembleRelease --stacktrace -w
